openapi: 3.0.0
info:
  title: Organiza API
  description: API para gerenciamento de usuários, autenticação e operações relacionadas.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Servidor local
paths:
  /register:
    post:
      summary: Registro de usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: senha123
      responses:
        '201':
          description: Usuário registrado com sucesso
        '400':
          description: Erro de validação ou usuário já registrado
  /login:
    post:
      summary: Login do usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: user@example.com
                password:
                  type: string
                  example: senha123
      responses:
        '200':
          description: Login bem-sucedido, retorna o token JWT
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI...
        '401':
          description: Credenciais inválidas
  /delete/{email}:
    delete:
      summary: Deletar usuário
      parameters:
        - name: email
          in: path
          required: true
          schema:
            type: string
          description: Email do usuário a ser deletado
      responses:
        '200':
          description: Usuário deletado com sucesso
        '404':
          description: Usuário não encontrado
        '500':
          description: Erro interno
  /api/protected:
    get:
      summary: Endpoint protegido
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Acesso permitido
        '403':
          description: Token ausente ou inválido
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
