openapi: 3.0.0
info:
  title: Organiza API
  version: 1.0.0
  description: API para autenticação e registro de usuários.

servers:
  - url: http://localhost:3000
    description: Servidor local de desenvolvimento

paths:
  /register:
    post:
      summary: Registrar novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '201':
          description: Usuário registrado com sucesso
        '400':
          description: Email já registrado

  /login:
    post:
      summary: Login de usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Login bem-sucedido, token retornado
        '401':
          description: Credenciais inválidas

  /api/protected:
    get:
      summary: Endpoint protegido
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Acesso permitido
        '403':
          description: Token não fornecido ou inválido

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
